# src/config/__init__.py
from .settings import *

__all__ = [
    "DEFAULT_INPUT_DIR",
    "DEFAULT_CHROMA_DB_DIR",
    "DEFAULT_INDEX_PERSIST_DIR",
    "DEFAULT_CHROMA_COLLECTION_NAME",
    "DEFAULT_OPENAI_EMBEDDING_MODEL",
    "DEFAULT_HUGGINGFACE_EMBEDDING_MODEL",
    "DEFAULT_OPENAI_LANGUAGE_MODEL",
    "DEFAULT_OLLAMA_LANGUAGE_MODEL",
    "DEFAULT_SIMILARITY_TOP_K",
    "DEFAULT_TEMPERATURE",
    "DEFAULT_LOG_LEVEL",
    "DEFAULT_LOG_FILE",
    "RECURSIVE_DIRECTORY_SEARCH",
]
